package com.personal.wine.model;

import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table w_setting
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class DeviceSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.device_name
     *
     * @mbg.generated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.led_color
     *
     * @mbg.generated
     */
    private String ledColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.led_brightness
     *
     * @mbg.generated
     */
    private Integer ledBrightness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.led_switch
     *
     * @mbg.generated
     */
    private Integer ledSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.glass_switch
     *
     * @mbg.generated
     */
    private Integer glassSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.alert_switch
     *
     * @mbg.generated
     */
    private Integer alertSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.door_switch
     *
     * @mbg.generated
     */
    private Integer doorSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.current_temperature
     *
     * @mbg.generated
     */
    private Integer currentTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.current_humidity
     *
     * @mbg.generated
     */
    private String currentHumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.temperature
     *
     * @mbg.generated
     */
    private Integer temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.low_temperature
     *
     * @mbg.generated
     */
    private Integer lowTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.high_temperature
     *
     * @mbg.generated
     */
    private Integer highTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.low_temperature_alert
     *
     * @mbg.generated
     */
    private Integer lowTemperatureAlert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.high_temperature_alert
     *
     * @mbg.generated
     */
    private Integer highTemperatureAlert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.lock_delay
     *
     * @mbg.generated
     */
    private Integer lockDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.fan_setting
     *
     * @mbg.generated
     */
    private Integer fanSetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.stop_power
     *
     * @mbg.generated
     */
    private Integer stopPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.rebound_power
     *
     * @mbg.generated
     */
    private Integer reboundPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.deicing_time
     *
     * @mbg.generated
     */
    private Integer deicingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.deicing_device_time
     *
     * @mbg.generated
     */
    private Integer deicingDeviceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_setting.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.id
     *
     * @return the value of w_setting.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.id
     *
     * @param id the value for w_setting.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.device_id
     *
     * @return the value of w_setting.device_id
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.device_id
     *
     * @param deviceId the value for w_setting.device_id
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.user_id
     *
     * @return the value of w_setting.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.user_id
     *
     * @param userId the value for w_setting.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.device_name
     *
     * @return the value of w_setting.device_name
     * @mbg.generated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.device_name
     *
     * @param deviceName the value for w_setting.device_name
     * @mbg.generated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.led_color
     *
     * @return the value of w_setting.led_color
     * @mbg.generated
     */
    public String getLedColor() {
        return ledColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.led_color
     *
     * @param ledColor the value for w_setting.led_color
     * @mbg.generated
     */
    public void setLedColor(String ledColor) {
        this.ledColor = ledColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.led_brightness
     *
     * @return the value of w_setting.led_brightness
     * @mbg.generated
     */
    public Integer getLedBrightness() {
        return ledBrightness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.led_brightness
     *
     * @param ledBrightness the value for w_setting.led_brightness
     * @mbg.generated
     */
    public void setLedBrightness(Integer ledBrightness) {
        this.ledBrightness = ledBrightness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.led_switch
     *
     * @return the value of w_setting.led_switch
     * @mbg.generated
     */
    public Integer getLedSwitch() {
        return ledSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.led_switch
     *
     * @param ledSwitch the value for w_setting.led_switch
     * @mbg.generated
     */
    public void setLedSwitch(Integer ledSwitch) {
        this.ledSwitch = ledSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.glass_switch
     *
     * @return the value of w_setting.glass_switch
     * @mbg.generated
     */
    public Integer getGlassSwitch() {
        return glassSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.glass_switch
     *
     * @param glassSwitch the value for w_setting.glass_switch
     * @mbg.generated
     */
    public void setGlassSwitch(Integer glassSwitch) {
        this.glassSwitch = glassSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.alert_switch
     *
     * @return the value of w_setting.alert_switch
     * @mbg.generated
     */
    public Integer getAlertSwitch() {
        return alertSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.alert_switch
     *
     * @param alertSwitch the value for w_setting.alert_switch
     * @mbg.generated
     */
    public void setAlertSwitch(Integer alertSwitch) {
        this.alertSwitch = alertSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.door_switch
     *
     * @return the value of w_setting.door_switch
     * @mbg.generated
     */
    public Integer getDoorSwitch() {
        return doorSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.door_switch
     *
     * @param doorSwitch the value for w_setting.door_switch
     * @mbg.generated
     */
    public void setDoorSwitch(Integer doorSwitch) {
        this.doorSwitch = doorSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.current_temperature
     *
     * @return the value of w_setting.current_temperature
     * @mbg.generated
     */
    public Integer getCurrentTemperature() {
        return currentTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.current_temperature
     *
     * @param currentTemperature the value for w_setting.current_temperature
     * @mbg.generated
     */
    public void setCurrentTemperature(Integer currentTemperature) {
        this.currentTemperature = currentTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.current_humidity
     *
     * @return the value of w_setting.current_humidity
     * @mbg.generated
     */
    public String getCurrentHumidity() {
        return currentHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.current_humidity
     *
     * @param currentHumidity the value for w_setting.current_humidity
     * @mbg.generated
     */
    public void setCurrentHumidity(String currentHumidity) {
        this.currentHumidity = currentHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.temperature
     *
     * @return the value of w_setting.temperature
     * @mbg.generated
     */
    public Integer getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.temperature
     *
     * @param temperature the value for w_setting.temperature
     * @mbg.generated
     */
    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.low_temperature
     *
     * @return the value of w_setting.low_temperature
     * @mbg.generated
     */
    public Integer getLowTemperature() {
        return lowTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.low_temperature
     *
     * @param lowTemperature the value for w_setting.low_temperature
     * @mbg.generated
     */
    public void setLowTemperature(Integer lowTemperature) {
        this.lowTemperature = lowTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.high_temperature
     *
     * @return the value of w_setting.high_temperature
     * @mbg.generated
     */
    public Integer getHighTemperature() {
        return highTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.high_temperature
     *
     * @param highTemperature the value for w_setting.high_temperature
     * @mbg.generated
     */
    public void setHighTemperature(Integer highTemperature) {
        this.highTemperature = highTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.low_temperature_alert
     *
     * @return the value of w_setting.low_temperature_alert
     * @mbg.generated
     */
    public Integer getLowTemperatureAlert() {
        return lowTemperatureAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.low_temperature_alert
     *
     * @param lowTemperatureAlert the value for w_setting.low_temperature_alert
     * @mbg.generated
     */
    public void setLowTemperatureAlert(Integer lowTemperatureAlert) {
        this.lowTemperatureAlert = lowTemperatureAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.high_temperature_alert
     *
     * @return the value of w_setting.high_temperature_alert
     * @mbg.generated
     */
    public Integer getHighTemperatureAlert() {
        return highTemperatureAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.high_temperature_alert
     *
     * @param highTemperatureAlert the value for w_setting.high_temperature_alert
     * @mbg.generated
     */
    public void setHighTemperatureAlert(Integer highTemperatureAlert) {
        this.highTemperatureAlert = highTemperatureAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.lock_delay
     *
     * @return the value of w_setting.lock_delay
     * @mbg.generated
     */
    public Integer getLockDelay() {
        return lockDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.lock_delay
     *
     * @param lockDelay the value for w_setting.lock_delay
     * @mbg.generated
     */
    public void setLockDelay(Integer lockDelay) {
        this.lockDelay = lockDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.fan_setting
     *
     * @return the value of w_setting.fan_setting
     * @mbg.generated
     */
    public Integer getFanSetting() {
        return fanSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.fan_setting
     *
     * @param fanSetting the value for w_setting.fan_setting
     * @mbg.generated
     */
    public void setFanSetting(Integer fanSetting) {
        this.fanSetting = fanSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.stop_power
     *
     * @return the value of w_setting.stop_power
     * @mbg.generated
     */
    public Integer getStopPower() {
        return stopPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.stop_power
     *
     * @param stopPower the value for w_setting.stop_power
     * @mbg.generated
     */
    public void setStopPower(Integer stopPower) {
        this.stopPower = stopPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.rebound_power
     *
     * @return the value of w_setting.rebound_power
     * @mbg.generated
     */
    public Integer getReboundPower() {
        return reboundPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.rebound_power
     *
     * @param reboundPower the value for w_setting.rebound_power
     * @mbg.generated
     */
    public void setReboundPower(Integer reboundPower) {
        this.reboundPower = reboundPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.deicing_time
     *
     * @return the value of w_setting.deicing_time
     * @mbg.generated
     */
    public Integer getDeicingTime() {
        return deicingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.deicing_time
     *
     * @param deicingTime the value for w_setting.deicing_time
     * @mbg.generated
     */
    public void setDeicingTime(Integer deicingTime) {
        this.deicingTime = deicingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.deicing_device_time
     *
     * @return the value of w_setting.deicing_device_time
     * @mbg.generated
     */
    public Integer getDeicingDeviceTime() {
        return deicingDeviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.deicing_device_time
     *
     * @param deicingDeviceTime the value for w_setting.deicing_device_time
     * @mbg.generated
     */
    public void setDeicingDeviceTime(Integer deicingDeviceTime) {
        this.deicingDeviceTime = deicingDeviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_setting.create_time
     *
     * @return the value of w_setting.create_time
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_setting.create_time
     *
     * @param createTime the value for w_setting.create_time
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}