package com.personal.wine.model;

import java.util.ArrayList;
import java.util.List;

public class DeviceSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public DeviceSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIsNull() {
            addCriterion("device_name is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIsNotNull() {
            addCriterion("device_name is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNameEqualTo(String value) {
            addCriterion("device_name =", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotEqualTo(String value) {
            addCriterion("device_name <>", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameGreaterThan(String value) {
            addCriterion("device_name >", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
            addCriterion("device_name >=", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLessThan(String value) {
            addCriterion("device_name <", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLessThanOrEqualTo(String value) {
            addCriterion("device_name <=", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLike(String value) {
            addCriterion("device_name like", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotLike(String value) {
            addCriterion("device_name not like", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIn(List<String> values) {
            addCriterion("device_name in", values, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotIn(List<String> values) {
            addCriterion("device_name not in", values, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameBetween(String value1, String value2) {
            addCriterion("device_name between", value1, value2, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotBetween(String value1, String value2) {
            addCriterion("device_name not between", value1, value2, "deviceName");
            return (Criteria) this;
        }

        public Criteria andLedColorIsNull() {
            addCriterion("led_color is null");
            return (Criteria) this;
        }

        public Criteria andLedColorIsNotNull() {
            addCriterion("led_color is not null");
            return (Criteria) this;
        }

        public Criteria andLedColorEqualTo(String value) {
            addCriterion("led_color =", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorNotEqualTo(String value) {
            addCriterion("led_color <>", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorGreaterThan(String value) {
            addCriterion("led_color >", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorGreaterThanOrEqualTo(String value) {
            addCriterion("led_color >=", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorLessThan(String value) {
            addCriterion("led_color <", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorLessThanOrEqualTo(String value) {
            addCriterion("led_color <=", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorLike(String value) {
            addCriterion("led_color like", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorNotLike(String value) {
            addCriterion("led_color not like", value, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorIn(List<String> values) {
            addCriterion("led_color in", values, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorNotIn(List<String> values) {
            addCriterion("led_color not in", values, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorBetween(String value1, String value2) {
            addCriterion("led_color between", value1, value2, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedColorNotBetween(String value1, String value2) {
            addCriterion("led_color not between", value1, value2, "ledColor");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessIsNull() {
            addCriterion("led_brightness is null");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessIsNotNull() {
            addCriterion("led_brightness is not null");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessEqualTo(Integer value) {
            addCriterion("led_brightness =", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessNotEqualTo(Integer value) {
            addCriterion("led_brightness <>", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessGreaterThan(Integer value) {
            addCriterion("led_brightness >", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessGreaterThanOrEqualTo(Integer value) {
            addCriterion("led_brightness >=", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessLessThan(Integer value) {
            addCriterion("led_brightness <", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessLessThanOrEqualTo(Integer value) {
            addCriterion("led_brightness <=", value, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessIn(List<Integer> values) {
            addCriterion("led_brightness in", values, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessNotIn(List<Integer> values) {
            addCriterion("led_brightness not in", values, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessBetween(Integer value1, Integer value2) {
            addCriterion("led_brightness between", value1, value2, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedBrightnessNotBetween(Integer value1, Integer value2) {
            addCriterion("led_brightness not between", value1, value2, "ledBrightness");
            return (Criteria) this;
        }

        public Criteria andLedSwitchIsNull() {
            addCriterion("led_switch is null");
            return (Criteria) this;
        }

        public Criteria andLedSwitchIsNotNull() {
            addCriterion("led_switch is not null");
            return (Criteria) this;
        }

        public Criteria andLedSwitchEqualTo(Integer value) {
            addCriterion("led_switch =", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchNotEqualTo(Integer value) {
            addCriterion("led_switch <>", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchGreaterThan(Integer value) {
            addCriterion("led_switch >", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("led_switch >=", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchLessThan(Integer value) {
            addCriterion("led_switch <", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("led_switch <=", value, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchIn(List<Integer> values) {
            addCriterion("led_switch in", values, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchNotIn(List<Integer> values) {
            addCriterion("led_switch not in", values, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchBetween(Integer value1, Integer value2) {
            addCriterion("led_switch between", value1, value2, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andLedSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("led_switch not between", value1, value2, "ledSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchIsNull() {
            addCriterion("glass_switch is null");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchIsNotNull() {
            addCriterion("glass_switch is not null");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchEqualTo(Integer value) {
            addCriterion("glass_switch =", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchNotEqualTo(Integer value) {
            addCriterion("glass_switch <>", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchGreaterThan(Integer value) {
            addCriterion("glass_switch >", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("glass_switch >=", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchLessThan(Integer value) {
            addCriterion("glass_switch <", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("glass_switch <=", value, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchIn(List<Integer> values) {
            addCriterion("glass_switch in", values, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchNotIn(List<Integer> values) {
            addCriterion("glass_switch not in", values, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchBetween(Integer value1, Integer value2) {
            addCriterion("glass_switch between", value1, value2, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andGlassSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("glass_switch not between", value1, value2, "glassSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchIsNull() {
            addCriterion("alert_switch is null");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchIsNotNull() {
            addCriterion("alert_switch is not null");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchEqualTo(Integer value) {
            addCriterion("alert_switch =", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchNotEqualTo(Integer value) {
            addCriterion("alert_switch <>", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchGreaterThan(Integer value) {
            addCriterion("alert_switch >", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("alert_switch >=", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchLessThan(Integer value) {
            addCriterion("alert_switch <", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("alert_switch <=", value, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchIn(List<Integer> values) {
            addCriterion("alert_switch in", values, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchNotIn(List<Integer> values) {
            addCriterion("alert_switch not in", values, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchBetween(Integer value1, Integer value2) {
            addCriterion("alert_switch between", value1, value2, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andAlertSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("alert_switch not between", value1, value2, "alertSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchIsNull() {
            addCriterion("door_switch is null");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchIsNotNull() {
            addCriterion("door_switch is not null");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchEqualTo(Integer value) {
            addCriterion("door_switch =", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchNotEqualTo(Integer value) {
            addCriterion("door_switch <>", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchGreaterThan(Integer value) {
            addCriterion("door_switch >", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("door_switch >=", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchLessThan(Integer value) {
            addCriterion("door_switch <", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("door_switch <=", value, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchIn(List<Integer> values) {
            addCriterion("door_switch in", values, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchNotIn(List<Integer> values) {
            addCriterion("door_switch not in", values, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchBetween(Integer value1, Integer value2) {
            addCriterion("door_switch between", value1, value2, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andDoorSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("door_switch not between", value1, value2, "doorSwitch");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureIsNull() {
            addCriterion("current_temperature is null");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureIsNotNull() {
            addCriterion("current_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureEqualTo(Integer value) {
            addCriterion("current_temperature =", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureNotEqualTo(Integer value) {
            addCriterion("current_temperature <>", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureGreaterThan(Integer value) {
            addCriterion("current_temperature >", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_temperature >=", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureLessThan(Integer value) {
            addCriterion("current_temperature <", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("current_temperature <=", value, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureIn(List<Integer> values) {
            addCriterion("current_temperature in", values, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureNotIn(List<Integer> values) {
            addCriterion("current_temperature not in", values, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("current_temperature between", value1, value2, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("current_temperature not between", value1, value2, "currentTemperature");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityIsNull() {
            addCriterion("current_humidity is null");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityIsNotNull() {
            addCriterion("current_humidity is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityEqualTo(String value) {
            addCriterion("current_humidity =", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityNotEqualTo(String value) {
            addCriterion("current_humidity <>", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityGreaterThan(String value) {
            addCriterion("current_humidity >", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityGreaterThanOrEqualTo(String value) {
            addCriterion("current_humidity >=", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityLessThan(String value) {
            addCriterion("current_humidity <", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityLessThanOrEqualTo(String value) {
            addCriterion("current_humidity <=", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityLike(String value) {
            addCriterion("current_humidity like", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityNotLike(String value) {
            addCriterion("current_humidity not like", value, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityIn(List<String> values) {
            addCriterion("current_humidity in", values, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityNotIn(List<String> values) {
            addCriterion("current_humidity not in", values, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityBetween(String value1, String value2) {
            addCriterion("current_humidity between", value1, value2, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andCurrentHumidityNotBetween(String value1, String value2) {
            addCriterion("current_humidity not between", value1, value2, "currentHumidity");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(Integer value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(Integer value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(Integer value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(Integer value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<Integer> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<Integer> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureIsNull() {
            addCriterion("low_temperature is null");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureIsNotNull() {
            addCriterion("low_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureEqualTo(Integer value) {
            addCriterion("low_temperature =", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureNotEqualTo(Integer value) {
            addCriterion("low_temperature <>", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureGreaterThan(Integer value) {
            addCriterion("low_temperature >", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("low_temperature >=", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureLessThan(Integer value) {
            addCriterion("low_temperature <", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("low_temperature <=", value, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureIn(List<Integer> values) {
            addCriterion("low_temperature in", values, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureNotIn(List<Integer> values) {
            addCriterion("low_temperature not in", values, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("low_temperature between", value1, value2, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("low_temperature not between", value1, value2, "lowTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureIsNull() {
            addCriterion("high_temperature is null");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureIsNotNull() {
            addCriterion("high_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureEqualTo(Integer value) {
            addCriterion("high_temperature =", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureNotEqualTo(Integer value) {
            addCriterion("high_temperature <>", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureGreaterThan(Integer value) {
            addCriterion("high_temperature >", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("high_temperature >=", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureLessThan(Integer value) {
            addCriterion("high_temperature <", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("high_temperature <=", value, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureIn(List<Integer> values) {
            addCriterion("high_temperature in", values, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureNotIn(List<Integer> values) {
            addCriterion("high_temperature not in", values, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("high_temperature between", value1, value2, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("high_temperature not between", value1, value2, "highTemperature");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertIsNull() {
            addCriterion("low_temperature_alert is null");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertIsNotNull() {
            addCriterion("low_temperature_alert is not null");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertEqualTo(Integer value) {
            addCriterion("low_temperature_alert =", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertNotEqualTo(Integer value) {
            addCriterion("low_temperature_alert <>", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertGreaterThan(Integer value) {
            addCriterion("low_temperature_alert >", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertGreaterThanOrEqualTo(Integer value) {
            addCriterion("low_temperature_alert >=", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertLessThan(Integer value) {
            addCriterion("low_temperature_alert <", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertLessThanOrEqualTo(Integer value) {
            addCriterion("low_temperature_alert <=", value, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertIn(List<Integer> values) {
            addCriterion("low_temperature_alert in", values, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertNotIn(List<Integer> values) {
            addCriterion("low_temperature_alert not in", values, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertBetween(Integer value1, Integer value2) {
            addCriterion("low_temperature_alert between", value1, value2, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLowTemperatureAlertNotBetween(Integer value1, Integer value2) {
            addCriterion("low_temperature_alert not between", value1, value2, "lowTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertIsNull() {
            addCriterion("high_temperature_alert is null");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertIsNotNull() {
            addCriterion("high_temperature_alert is not null");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertEqualTo(Integer value) {
            addCriterion("high_temperature_alert =", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertNotEqualTo(Integer value) {
            addCriterion("high_temperature_alert <>", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertGreaterThan(Integer value) {
            addCriterion("high_temperature_alert >", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertGreaterThanOrEqualTo(Integer value) {
            addCriterion("high_temperature_alert >=", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertLessThan(Integer value) {
            addCriterion("high_temperature_alert <", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertLessThanOrEqualTo(Integer value) {
            addCriterion("high_temperature_alert <=", value, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertIn(List<Integer> values) {
            addCriterion("high_temperature_alert in", values, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertNotIn(List<Integer> values) {
            addCriterion("high_temperature_alert not in", values, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertBetween(Integer value1, Integer value2) {
            addCriterion("high_temperature_alert between", value1, value2, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andHighTemperatureAlertNotBetween(Integer value1, Integer value2) {
            addCriterion("high_temperature_alert not between", value1, value2, "highTemperatureAlert");
            return (Criteria) this;
        }

        public Criteria andLockDelayIsNull() {
            addCriterion("lock_delay is null");
            return (Criteria) this;
        }

        public Criteria andLockDelayIsNotNull() {
            addCriterion("lock_delay is not null");
            return (Criteria) this;
        }

        public Criteria andLockDelayEqualTo(Integer value) {
            addCriterion("lock_delay =", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayNotEqualTo(Integer value) {
            addCriterion("lock_delay <>", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayGreaterThan(Integer value) {
            addCriterion("lock_delay >", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("lock_delay >=", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayLessThan(Integer value) {
            addCriterion("lock_delay <", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayLessThanOrEqualTo(Integer value) {
            addCriterion("lock_delay <=", value, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayIn(List<Integer> values) {
            addCriterion("lock_delay in", values, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayNotIn(List<Integer> values) {
            addCriterion("lock_delay not in", values, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayBetween(Integer value1, Integer value2) {
            addCriterion("lock_delay between", value1, value2, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andLockDelayNotBetween(Integer value1, Integer value2) {
            addCriterion("lock_delay not between", value1, value2, "lockDelay");
            return (Criteria) this;
        }

        public Criteria andFanSettingIsNull() {
            addCriterion("fan_setting is null");
            return (Criteria) this;
        }

        public Criteria andFanSettingIsNotNull() {
            addCriterion("fan_setting is not null");
            return (Criteria) this;
        }

        public Criteria andFanSettingEqualTo(Integer value) {
            addCriterion("fan_setting =", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingNotEqualTo(Integer value) {
            addCriterion("fan_setting <>", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingGreaterThan(Integer value) {
            addCriterion("fan_setting >", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingGreaterThanOrEqualTo(Integer value) {
            addCriterion("fan_setting >=", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingLessThan(Integer value) {
            addCriterion("fan_setting <", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingLessThanOrEqualTo(Integer value) {
            addCriterion("fan_setting <=", value, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingIn(List<Integer> values) {
            addCriterion("fan_setting in", values, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingNotIn(List<Integer> values) {
            addCriterion("fan_setting not in", values, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingBetween(Integer value1, Integer value2) {
            addCriterion("fan_setting between", value1, value2, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andFanSettingNotBetween(Integer value1, Integer value2) {
            addCriterion("fan_setting not between", value1, value2, "fanSetting");
            return (Criteria) this;
        }

        public Criteria andStopPowerIsNull() {
            addCriterion("stop_power is null");
            return (Criteria) this;
        }

        public Criteria andStopPowerIsNotNull() {
            addCriterion("stop_power is not null");
            return (Criteria) this;
        }

        public Criteria andStopPowerEqualTo(Integer value) {
            addCriterion("stop_power =", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerNotEqualTo(Integer value) {
            addCriterion("stop_power <>", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerGreaterThan(Integer value) {
            addCriterion("stop_power >", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("stop_power >=", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerLessThan(Integer value) {
            addCriterion("stop_power <", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerLessThanOrEqualTo(Integer value) {
            addCriterion("stop_power <=", value, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerIn(List<Integer> values) {
            addCriterion("stop_power in", values, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerNotIn(List<Integer> values) {
            addCriterion("stop_power not in", values, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerBetween(Integer value1, Integer value2) {
            addCriterion("stop_power between", value1, value2, "stopPower");
            return (Criteria) this;
        }

        public Criteria andStopPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("stop_power not between", value1, value2, "stopPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerIsNull() {
            addCriterion("rebound_power is null");
            return (Criteria) this;
        }

        public Criteria andReboundPowerIsNotNull() {
            addCriterion("rebound_power is not null");
            return (Criteria) this;
        }

        public Criteria andReboundPowerEqualTo(Integer value) {
            addCriterion("rebound_power =", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerNotEqualTo(Integer value) {
            addCriterion("rebound_power <>", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerGreaterThan(Integer value) {
            addCriterion("rebound_power >", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("rebound_power >=", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerLessThan(Integer value) {
            addCriterion("rebound_power <", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerLessThanOrEqualTo(Integer value) {
            addCriterion("rebound_power <=", value, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerIn(List<Integer> values) {
            addCriterion("rebound_power in", values, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerNotIn(List<Integer> values) {
            addCriterion("rebound_power not in", values, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerBetween(Integer value1, Integer value2) {
            addCriterion("rebound_power between", value1, value2, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andReboundPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("rebound_power not between", value1, value2, "reboundPower");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeIsNull() {
            addCriterion("deicing_time is null");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeIsNotNull() {
            addCriterion("deicing_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeEqualTo(Integer value) {
            addCriterion("deicing_time =", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeNotEqualTo(Integer value) {
            addCriterion("deicing_time <>", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeGreaterThan(Integer value) {
            addCriterion("deicing_time >", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deicing_time >=", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeLessThan(Integer value) {
            addCriterion("deicing_time <", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeLessThanOrEqualTo(Integer value) {
            addCriterion("deicing_time <=", value, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeIn(List<Integer> values) {
            addCriterion("deicing_time in", values, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeNotIn(List<Integer> values) {
            addCriterion("deicing_time not in", values, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeBetween(Integer value1, Integer value2) {
            addCriterion("deicing_time between", value1, value2, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("deicing_time not between", value1, value2, "deicingTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeIsNull() {
            addCriterion("deicing_device_time is null");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeIsNotNull() {
            addCriterion("deicing_device_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeEqualTo(Integer value) {
            addCriterion("deicing_device_time =", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeNotEqualTo(Integer value) {
            addCriterion("deicing_device_time <>", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeGreaterThan(Integer value) {
            addCriterion("deicing_device_time >", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deicing_device_time >=", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeLessThan(Integer value) {
            addCriterion("deicing_device_time <", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeLessThanOrEqualTo(Integer value) {
            addCriterion("deicing_device_time <=", value, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeIn(List<Integer> values) {
            addCriterion("deicing_device_time in", values, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeNotIn(List<Integer> values) {
            addCriterion("deicing_device_time not in", values, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeBetween(Integer value1, Integer value2) {
            addCriterion("deicing_device_time between", value1, value2, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andDeicingDeviceTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("deicing_device_time not between", value1, value2, "deicingDeviceTime");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIsNull() {
            addCriterion("alert_type is null");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIsNotNull() {
            addCriterion("alert_type is not null");
            return (Criteria) this;
        }

        public Criteria andAlertTypeEqualTo(Integer value) {
            addCriterion("alert_type =", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotEqualTo(Integer value) {
            addCriterion("alert_type <>", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeGreaterThan(Integer value) {
            addCriterion("alert_type >", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("alert_type >=", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeLessThan(Integer value) {
            addCriterion("alert_type <", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeLessThanOrEqualTo(Integer value) {
            addCriterion("alert_type <=", value, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeIn(List<Integer> values) {
            addCriterion("alert_type in", values, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotIn(List<Integer> values) {
            addCriterion("alert_type not in", values, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeBetween(Integer value1, Integer value2) {
            addCriterion("alert_type between", value1, value2, "alertType");
            return (Criteria) this;
        }

        public Criteria andAlertTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("alert_type not between", value1, value2, "alertType");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceIsNull() {
            addCriterion("default_device is null");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceIsNotNull() {
            addCriterion("default_device is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceEqualTo(Integer value) {
            addCriterion("default_device =", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceNotEqualTo(Integer value) {
            addCriterion("default_device <>", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceGreaterThan(Integer value) {
            addCriterion("default_device >", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_device >=", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceLessThan(Integer value) {
            addCriterion("default_device <", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceLessThanOrEqualTo(Integer value) {
            addCriterion("default_device <=", value, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceIn(List<Integer> values) {
            addCriterion("default_device in", values, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceNotIn(List<Integer> values) {
            addCriterion("default_device not in", values, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceBetween(Integer value1, Integer value2) {
            addCriterion("default_device between", value1, value2, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andDefaultDeviceNotBetween(Integer value1, Integer value2) {
            addCriterion("default_device not between", value1, value2, "defaultDevice");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_setting
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_setting
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}