package com.personal.wine.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table w_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SystemUser {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     * Database Column Remarks:
     *   用户密码（MD5）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     * Database Column Remarks:
     *   创建时间字符串毫秒值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * Database Column Remarks:
     *   用户是否可用0：不可用；1：可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.id
     *
     * @return the value of w_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.id
     *
     * @param id the value for w_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.user_name
     *
     * @return the value of w_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.user_name
     *
     * @param userName the value for w_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.phone
     *
     * @return the value of w_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.phone
     *
     * @param phone the value for w_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.photo
     *
     * @return the value of w_user.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.photo
     *
     * @param photo the value for w_user.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.password
     *
     * @return the value of w_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.password
     *
     * @param password the value for w_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.role
     *
     * @return the value of w_user.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.role
     *
     * @param role the value for w_user.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.create_time
     *
     * @return the value of w_user.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.create_time
     *
     * @param createTime the value for w_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.update_time
     *
     * @return the value of w_user.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.update_time
     *
     * @param updateTime the value for w_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.flag
     *
     * @return the value of w_user.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.flag
     *
     * @param flag the value for w_user.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}