package com.personal.wine.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table w_warning
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Warning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_warning.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   报警的设备的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_warning.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     * Database Column Remarks:
     *   报警类型：1.温度上限 2.温度下限，3.开门警报 4.展台警报
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_warning.warning_type
     *
     * @mbg.generated
     */
    private Integer warningType;

    /**
     * Database Column Remarks:
     *   报警的时间 毫秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_warning.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * Database Column Remarks:
     *   警报状态，即是否需要报警0：不需要，1：需要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_warning.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_warning.id
     *
     * @return the value of w_warning.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_warning.id
     *
     * @param id the value for w_warning.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_warning.device_id
     *
     * @return the value of w_warning.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_warning.device_id
     *
     * @param deviceId the value for w_warning.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_warning.warning_type
     *
     * @return the value of w_warning.warning_type
     *
     * @mbg.generated
     */
    public Integer getWarningType() {
        return warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_warning.warning_type
     *
     * @param warningType the value for w_warning.warning_type
     *
     * @mbg.generated
     */
    public void setWarningType(Integer warningType) {
        this.warningType = warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_warning.update_time
     *
     * @return the value of w_warning.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_warning.update_time
     *
     * @param updateTime the value for w_warning.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_warning.status
     *
     * @return the value of w_warning.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_warning.status
     *
     * @param status the value for w_warning.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}